### ISSUE TITLE
Music App + Nuxt

### ISSUE THREAD

**Issue by pi0** [microeinhundert/music-app-electron#1]
Hi. This is just an amazing project ❤️ As you are in early stages I want to ask you about any interest migrating to [Nuxt.js](https://nuxtjs.org) as we are working on a super easy electron integration module. And I suppose some enhancements for this awesome project:

- Less code and Cleaner project structure
- Support both Web/Mobile and Electron targets with single codebase and toolchain
- Easier Auth stuff and leverage `serverMiddleware`
- Easier transitions

Just wanted to inform you with this suggestion as i've not found an email contact adress. Feel free closing if you saw this :)

Best wishes.

**Comment by microeinhundert** [comment]
@pi0 I saw it a bit late, but thank you. I thought about Nuxt.js but i think it's not necessary for a project that is primarily a desktop app, correct me if i'm wrong. How do you think the code can be cleaned up? I used the single file components to make every component as universal as possible without having duplicated components that do almost the same thing.

**Comment by pi0** [comment]
Hi, @microeinhundert. I agree that such project would be primarily designed for Desktop environments. But just thought would be better refactor [music-app](https://github.com/microeinhundert/music-app) and this repo in a single code base. Nuxt (while is still for the web) is going further than it and can remove all unnecessary boilerplate for web pack builds and potentially allow having a fully offline working PWA version of this app which I think would be really inspiring for production-grade desktop apps like Spotify.
Also, don't worry about extra works from your side for that migration I can help for that when Nuxt Electron module was ready. Just wanted to ask if you are willing to officially switch to nuxt then? Personally, i'm really interested having spare time on this project and make it a real Ready to Use Spotify client.

**Comment by microeinhundert** [comment]
@pi0 I would really like to switch to Nuxt if its not that much extra work.
